title: dreimux
email: dreimux@gmail.com
description: 3D Generalist, Gaming enthusiast, Computerphile.

twitter_username: dreimux
reddit_username: dreimux
instagram_username: dreimux
youtube_username: channel
facebook_username: dreimux
github_username: dreimux
artstation_username: dreimux

thingiverse_username: dreimux
myminifactory_username: dreimux




theme: jekyll-theme-minimal
